### ISSUE TITLE
Subway validation crashes with exception on repeated nodes on a way

### ISSUE THREAD

**Issue by alexey-zakharenkov** [mapsme/subways#58]
When there exist two identical nodes on a way:
..., p1(x1,y1), p2(x,y), p3(x,y), p4(x4, y4), ...

the project_on_segment(p, p2, p3) function fails to project point onto such a degenerated segment with the backtrace:

```
Traceback (most recent call last):
  File "subways/process_subways.py", line 363, in <module>
    c.extract_routes()
  File "subways/subway_structure.py", line 1033, in extract_routes
    route = Route(el, self, master)
  File "subways/subway_structure.py", line 734, in __init__
    self.project_stops_on_line(city)
  File "subways/subway_structure.py", line 553, in project_stops_on_line
    projected = [project_on_line(x.stop, self.tracks) for x in self.stops]
  File "subways/subway_structure.py", line 553, in <listcomp>
    projected = [project_on_line(x.stop, self.tracks) for x in self.stops]
  File "subways/subway_structure.py", line 96, in project_on_line
    proj = project_on_segment(p, line[seg], line[seg+1])
  File "subways/subway_structure.py", line 72, in project_on_segment
    u = ((p[0] - p1[0])*dp[0] + (p[1] - p1[1])*dp[1]) / d2
ZeroDivisionError: float division by zero
```

I think the script should ignore such segments and maybe generate a warning.
I'd suggest such a fix:

```
        try:
            u = ((p[0] - p1[0])*dp[0] + (p[1] - p1[1])*dp[1]) / d2
        except ZeroDivisionError:
            logging.warning("Repeated nodes on a way at {}".format(p1))
            return None
```

but then this warning would be generated multiple times for the same problematic spot.

**Comment by alexey-zakharenkov** [comment]
Fixed in [PR #59](https://github.com/mapsme/subways/pull/59). Please close the issue.
